variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375

stages:
  - build
  - restart
  - notifydone

.for_development:
  environment:
    name: development
  variables:
    DOCKER_IMAGE_TAG: latest
    DEPLOY_ENV: staging
  only:
    - develop

.for_release:
  environment:
    name: release

.build:
  stage: build
  variables:
    DOCKER_BUILDKIT: 1
  services:
    - docker:19-dind
  script:
    - docker version
    - echo $GCP_SA_KEY | base64 -d | docker login -u _json_key --password-stdin https://asia-southeast2-docker.pkg.dev
    - docker pull asia-southeast2-docker.pkg.dev/pmrms-362603/pmrms-repo/sippro/sippro-fe:${DOCKER_IMAGE_TAG} || true

    - docker build
      --build-arg GIT_COMMIT_SHA=${CI_COMMIT_SHA}
      --build-arg DEPLOY_ENV=${DEPLOY_ENV}
      --cache-from asia-southeast2-docker.pkg.dev/pmrms-362603/pmrms-repo/sippro/sippro-fe:${DOCKER_IMAGE_TAG}
      --tag asia-southeast2-docker.pkg.dev/pmrms-362603/pmrms-repo/sippro/sippro-fe:${DOCKER_IMAGE_TAG}
      --label org.label-schema.schema-version="1.0"
      --label org.label-schema.vcs-url="${CI_PROJECT_URL}.git"
      --label org.label-schema.vcs-ref="${CI_COMMIT_SHA}"
      .

    - docker push asia-southeast2-docker.pkg.dev/pmrms-362603/pmrms-repo/sippro/sippro-fe:${DOCKER_IMAGE_TAG}

.restart:
  stage: restart
  image: curlimages/curl
  script:
    - >
      curl -v -X POST https://bot.impstudio.id/restart -H "Content-Type: application/json" -d "{\"project\": \"sippro-fe\", \"env\": \"${DEPLOY_ENV}\" }"

notify_done:
  stage: notifydone
  image: curlimages/curl
  script:
    - >
      curl -X 'GET' 'http://halotec:halotec123@wa.halotec.my.id/api/sendText?phone=6281375432574&text=Staging%20sipro-fe%20Done!!&session=default'

development:publish:
  extends:
    - .build
    - .for_development

development:restart:
  extends:
    - .restart
    - .for_development

.prepare_release:
  extends: .build
  stage: build
  before_script:
    - DOCKER_IMAGE_TAG=${CI_COMMIT_TAG}
    - DEPLOY_ENV=production
    
release:publish:
  extends:
    - .prepare_release
    - .for_release
  rules:
    - if: $BY_TRIGGER == 'true'