const PenawaranStatusName = {
  Requested: 0,
  DocumentCompleted: 1,
  Confirmed: 2,
  FixConfirmed: 3,
  AssesmentOffering: 20,
  AssesmentOfferAccepted: 21,
  AssesmentInprogress: 22,
  AssesmentCompleted: 23,
  AssesmentLocationInProgress: 24,
  AssesmentLocationCompleted: 25,
  AssesmentAllCompleted: 26,
  AssesmentBackToUser: 27,
  AssesmentExpired: 28,
  AssesmentCanceled: 29,
  Rejected: 99,
  ValidSK: 50,
  Approved: 10,
  AllProcessDone: 60,
  DalamValidasi: 41,
  ValBANPTLAMRejected: 299,
  SKParaf1: 51,
  SKParaf2: 52,
  SKParaf3: 53,
  SKParaf4: 54,
  AssesmentLocationAssigned: 221,
  AssesmentLocationInProgress: 222,
  AssesmentLocationCompleted: 223,
  AssesmentLocationAllCompleted:226
};

export default PenawaranStatusName;